class Cliente:
    def __init__(self):
        id: str
        firstName: str
        lastName: str
        address: str
        city: str
        state: str
        zipCode: str
        phone: str
        email: str
        dateOfBirth: str
        registrationDate: str
        preferences: list